.PHONY = compile run jar runjar zip all clean

#TODO: edit with path to your javac (java compiler)
JC =  C:\Program Files\Java\jdk-11.0.4\bin\javac

#TODO: edit with path to your java (java runtime environment)
JRE =  C:\Program Files\Java\jdk-11.0.4\bin\java 

#TODO: edit with path to your module-path for javafx
MP = --module-path "C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib" --add-modules javafx.controls,javafx.fxml -Dfile.encoding=UTF-8 

#TODO: edit with your classpath from Eclipse 
CP = -classpath "C:\Users\Dan\eclipse-workspace\HelloFX_001;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.base.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.controls.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.fxml.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.graphics.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.media.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.swing.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.web.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx-swt.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\src.zip"

SRC = application/*.java   

APP = application.Main 

ARGS = 

compile:
	$(JC) $(CP) $(SRC) 

run:
	$(JRE) $(MP) $(CP) $(APP) $(ARGS)

jar:
	jar -cvmf manifest.txt executable.jar .

runjar:
	$(JRE) $(MP) -jar executable.jar $(ARGS)

# Create zip file for submitting to handin
zip: 
	zip -r ateam.zip .

#Eclipse's "Show Command Line"
all:
	C:\Program Files\Java\jdk-11.0.4\bin\javaw.exe --module-path "C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib" --add-modules javafx.controls,javafx.fxml -Dfile.encoding=Cp1252 -classpath "C:\Users\Dan\git\ateam-GUI\aTeam-CS400;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.base.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.controls.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.fxml.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.graphics.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.media.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.swing.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx.web.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\javafx-swt.jar;C:\Users\Dan\eclipse-workspace\javafx-sdk-11.0.2\lib\src.zip" application.Main

# Remove generated files
clean:
	rm -f application/*.class
	rm -f executable.jar
